"""Add description to Book

Revision ID: 485f2781feec
Revises: 059146ade574
Create Date: 2025-08-10 20:49:24.726029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485f2781feec'
down_revision = '059146ade574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
