"""Add uploader_id to Book

Revision ID: 6274bfcc9760
Revises: 485f2781feec
Create Date: 2025-08-10 21:01:18.267153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6274bfcc9760'
down_revision = '485f2781feec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
